/**
 * LIBRERIA DEGLI EVENTI DEL BASKET — solo dati, stesso formato del calcio (types.ts).
 * "goal: [d, l]" = d metri dalla linea di fondo attaccata (il ferro è a 1,6 m), l laterale.
 * La decisione tipica del basket: la palla cambia mano in fretta, la camera deve passare da un giocatore all'altro.
 * Ruoli: mid = playmaker, fwd = ali, def = lunghi.
 */
import type { EventDef } from './types';

const ALL = ['mid', 'fwd', 'def'] as const;

export const BASKET: EventDef[] = [
  // ---------------------------------------------------------------- AZIONI PRINCIPALI
  {
    id: 'b-contropiede',
    label: 'Contropiede',
    outcomeLabels: { goal: 'Contropiede e schiacciata!', save: 'Schiacciata sul ferro!', wide: 'Contropiede sprecato' },
    category: 'main',
    hint: 'Ripartenza! Corrono tutti!',
    weight: 1.2,
    importance: 1,
    ownsBall: true,
    holderGoalDist: [18, 24],
    roles: {
      carrier: { label: 'Portatore', pick: 'holder' },
      runner: { label: 'Schiacciatore', pick: 'player', side: 'attack', roles: ['fwd', 'mid'], advanced: true },
      chaser: { label: 'Difensore', pick: 'player', side: 'defense', roles: [...ALL], near: 'runner' },
    },
    steps: [
      { t: 0, do: 'move', who: 'carrier', to: { near: 'carrier', off: [4, 0] }, speed: 'run' },
      { t: 0, do: 'move', who: 'runner', to: { goal: [6, 3] }, speed: 'sprint' },
      { t: 0.3, do: 'follow', who: 'chaser', target: 'runner', off: [-1.5, -0.8], speed: 'run' },
      { t: 1.5, do: 'pass', from: 'carrier', to: 'runner' },
      { t: 1.7, do: 'release', who: ['carrier'] },
      { t: 1.9, do: 'move', who: 'runner', to: { goal: [2.2, 0.4] }, speed: 'sprint' },
      { t: 3.3, do: 'shoot', who: 'runner', outcome: 'goal' },
      { t: 3.3, do: 'release', who: ['chaser'] },
    ],
    cues: [
      { t: 0.9, signal: 'windUp', who: 'carrier', dur: 0.6 },   // si ferma e prepara il lancio
      { t: 2.4, signal: 'crowdRise', who: 'runner' },
      { t: 2.9, signal: 'windUp', who: 'runner', dur: 0.4 },
    ],
    decisive: 3.3,
    duration: 5,
    shots: [
      { from: 0, size: 'medium', subjects: ['carrier', 'ball'] },
      { from: 1.5, size: 'wide', subjects: ['runner', 'ball'] },
      { from: 2.2, size: 'medium', subjects: ['runner', 'ball', 'goal'] },
    ],
  },
  {
    id: 'b-tripla',
    label: 'Tiro da tre',
    outcomeLabels: { goal: 'Tripla!', save: 'Tripla: sul ferro!', wide: 'Tripla: solo tabellone' },
    category: 'main',
    hint: 'Scarica fuori per il tiro!',
    weight: 3,
    importance: 0.8,
    ownsBall: true,
    holderGoalDist: [4, 22],
    roles: {
      passer: { label: 'Playmaker', pick: 'holder' },
      shooter: { label: 'Tiratore', pick: 'player', side: 'attack', roles: ['fwd'] },
      defender: { label: 'Difensore', pick: 'player', side: 'defense', roles: [...ALL], near: 'shooter' },
    },
    steps: [
      { t: 0, do: 'move', who: 'shooter', to: { goal: [7.5, 4] }, speed: 'run' },
      { t: 0, do: 'move', who: 'passer', to: { near: 'passer', off: [1, 0] }, speed: 'jog' },
      { t: 0, do: 'follow', who: 'defender', target: 'shooter', off: [1.4, 0], speed: 'run' },
      { t: 1.4, do: 'pass', from: 'passer', to: 'shooter' },
      { t: 1.6, do: 'release', who: ['passer'] },
      { t: 2.5, do: 'pose', who: 'defender', pose: 'wave', dur: 1.0 }, // braccia alte a contestare
      { t: 2.7, do: 'shoot', who: 'shooter' },                         // esito deciso dal Director
      { t: 2.7, do: 'release', who: ['defender'] },
    ],
    cues: [
      { t: 0.9, signal: 'windUp', who: 'passer', dur: 0.5 },
      { t: 1.9, signal: 'windUp', who: 'shooter', dur: 0.8 },   // riceve, si ferma, piega le gambe
      { t: 2.0, signal: 'crowdRise', who: 'shooter' },
    ],
    decisive: 2.7,
    duration: 4.6,
    shots: [
      { from: 0, size: 'medium', subjects: ['passer', 'ball', ['shooter', 0.6]] },
      { from: 1.5, size: 'medium', subjects: ['shooter', 'ball', 'goal'] },
      { from: 2.7, size: 'medium', subjects: ['goal', 'ball', ['shooter', 0.5]] },
    ],
  },
  {
    id: 'b-penetrazione',
    label: 'Penetrazione',
    outcomeLabels: { goal: 'Penetrazione e canestro!', save: 'Appoggio sul ferro', wide: 'Appoggio sbagliato' },
    category: 'main',
    hint: 'Va dentro, va dentro!',
    weight: 2.5,
    importance: 0.8,
    ownsBall: true,
    holderGoalDist: [5, 16],
    roles: {
      driver: { label: 'Attaccante', pick: 'holder' },
      defender: { label: 'Difensore', pick: 'player', side: 'defense', roles: [...ALL], near: 'driver' },
      helper: { label: 'Aiuto', pick: 'player', side: 'defense', roles: ['def'], near: 'driver' },
    },
    steps: [
      { t: 0, do: 'move', who: 'driver', to: { goal: [6, 1] }, speed: 'run' },
      { t: 0, do: 'follow', who: 'defender', target: 'driver', off: [0.8, 0.6], speed: 'run' },
      { t: 0.9, do: 'move', who: 'driver', to: { goal: [2.6, -1] }, speed: 'sprint' },
      { t: 1.2, do: 'move', who: 'helper', to: { goal: [2.2, 0] }, speed: 'run' },
      { t: 2.4, do: 'shoot', who: 'driver' },
      { t: 2.4, do: 'release', who: ['defender'] },
      { t: 2.6, do: 'release', who: ['helper'] },
    ],
    cues: [
      { t: 0.8, signal: 'crowdRise', who: 'driver' },
      { t: 1.9, signal: 'windUp', who: 'driver', dur: 0.5 },   // terzo tempo: raccoglie la palla
    ],
    decisive: 2.4,
    duration: 4.2,
    shots: [
      { from: 0, size: 'medium', subjects: ['driver', 'ball', ['defender', 0.6]] },
      { from: 1.2, size: 'medium', subjects: ['driver', 'ball', 'goal'] },
    ],
  },
  {
    id: 'b-giropalla',
    label: 'Giro palla',
    outcomeLabels: { goal: 'Giro palla e canestro!', save: 'Giro palla: sul ferro', wide: 'Giro palla: errore' },
    category: 'main',
    hint: 'Fanno girare la palla, seguila!',
    weight: 2.5,
    importance: 0.9,
    ownsBall: true,
    holderGoalDist: [4, 20],
    roles: {
      a: { label: 'Playmaker', pick: 'holder' },
      b: { label: 'Ala', pick: 'player', side: 'attack', roles: ['fwd', 'mid'] },
      c: { label: 'Pivot', pick: 'player', side: 'attack', roles: ['def'] },
    },
    steps: [
      { t: 0, do: 'move', who: 'b', to: { goal: [6.5, -4.5] }, speed: 'run' },
      { t: 0, do: 'move', who: 'c', to: { goal: [3.2, 3.2] }, speed: 'run' },
      { t: 0.8, do: 'pass', from: 'a', to: 'b' },
      { t: 1.0, do: 'release', who: ['a'] },
      { t: 1.9, do: 'pass', from: 'b', to: 'c' },
      { t: 2.1, do: 'release', who: ['b'] },
      { t: 2.6, do: 'move', who: 'c', to: { goal: [2.4, 1.2] }, speed: 'jog' },
      { t: 3.2, do: 'shoot', who: 'c' },
    ],
    cues: [
      { t: 0.4, signal: 'windUp', who: 'a', dur: 0.4 },
      { t: 1.5, signal: 'windUp', who: 'b', dur: 0.4 },
      { t: 2.4, signal: 'crowdRise', who: 'c' },
      { t: 2.7, signal: 'windUp', who: 'c', dur: 0.5 },
    ],
    decisive: 3.2,
    duration: 5,
    shots: [
      { from: 0, size: 'medium', subjects: ['a', 'ball'] },
      { from: 0.9, size: 'medium', subjects: ['b', 'ball'] },
      { from: 2.0, size: 'medium', subjects: ['c', 'ball', 'goal'] },
    ],
  },
  {
    id: 'b-sfondamento',
    label: 'Sfondamento',
    category: 'main',
    hint: 'Quello si butta dentro a testa bassa!',
    weight: 1,
    importance: 0.6,
    ownsBall: true,
    exclusive: true,
    holderGoalDist: [4, 14],
    roles: {
      driver: { label: 'Attaccante', pick: 'holder' },
      defender: { label: 'Difensore', pick: 'player', side: 'defense', roles: [...ALL], near: 'driver' },
      referee: { label: 'Arbitro', pick: 'referee' },
      mate: { label: 'Compagno', pick: 'player', side: 'attack', roles: [...ALL], near: 'driver' },
    },
    steps: [
      { t: 0, do: 'move', who: 'driver', to: { goal: [3, 0] }, speed: 'sprint' },
      { t: 0, do: 'move', who: 'defender', to: { goal: [3.6, 0] }, speed: 'run' },
      { t: 1.9, do: 'pose', who: 'driver', pose: 'shove', dur: 0.5, face: 'defender' },
      { t: 2.0, do: 'pose', who: 'defender', pose: 'fall', dur: 2.4 },
      { t: 2.2, do: 'whistle' },
      { t: 2.4, do: 'move', who: 'referee', to: { near: 'defender', off: [-1.5, -2] }, speed: 'run' },
      { t: 3.0, do: 'pose', who: 'driver', pose: 'protest', dur: 2.5, face: 'referee' },
      { t: 3.5, do: 'move', who: 'mate', to: { near: 'driver', off: [0.8, 0.8] }, speed: 'run' },
      { t: 3.8, do: 'pose', who: 'mate', pose: 'argue', dur: 2, face: 'referee' },
      { t: 4.3, do: 'pose', who: 'referee', pose: 'card', dur: 1.6 },
      { t: 6.5, do: 'restart', side: 'defense' }, // sfondamento: palla alla difesa
      { t: 6.5, do: 'release' },
    ],
    cues: [
      { t: 1.0, signal: 'crowdRise', who: 'driver' },
      { t: 1.2, signal: 'crouch', who: 'defender', dur: 0.7 },   // piedi piantati: aspetta il contatto
    ],
    decisive: 2.0,
    duration: 7,
    shots: [
      { from: 0, size: 'medium', subjects: ['driver', 'defender', 'ball'] },
      { from: 2.4, size: 'medium', subjects: ['defender', 'referee', ['driver', 0.7]] },
    ],
  },
  {
    id: 'b-esultanza',
    label: 'Esultanza',
    category: 'main',
    weight: 0,
    importance: 0.6,
    trigger: 'goal',
    roles: { scorer: { label: 'Marcatore', pick: 'scorer' } },
    steps: [], // pugno al cielo mentre torna in difesa: lo recita la partita
    cues: [{ t: 0, signal: 'crowdRise', who: 'scorer' }],
    decisive: 1.0,
    duration: 2.2,
    shots: [{ from: 0, size: 'close', subjects: ['scorer'] }],
  },

  // ---------------------------------------------------------------- EVENTI RARI
  {
    id: 'stella',
    label: 'Stella cadente!',
    category: 'rare',
    hint: 'Ma la gente guarda in alto...',
    weight: 1,
    importance: 1,
    once: true,
    roles: {},
    steps: [{ t: 2.0, do: 'effect', effect: 'shootingStar' }],
    cues: [{ t: 0, signal: 'crowdLookUp', dur: 3.6 }],
    decisive: 2.65,
    duration: 4.4,
    shots: [{ from: 0, size: 'close', subjects: ['star'] }],
  },

  // ---------------------------------------------------------------- DISTRAZIONI
  {
    id: 'b-scivolata',
    label: 'Scivolata sul parquet',
    category: 'distraction',
    hint: 'Qualcuno sta per scivolare...',
    weight: 2,
    importance: 0.45,
    roles: {
      faller: { label: 'Giocatore', pick: 'player', side: 'attack', roles: [...ALL], farFromBall: true },
      helper: { label: 'Compagno', pick: 'player', side: 'attack', roles: [...ALL], near: 'faller' },
    },
    steps: [
      { t: 0, do: 'move', who: 'faller', to: { near: 'faller', off: [4, 1.5] }, speed: 'sprint' },
      { t: 1.4, do: 'pose', who: 'faller', pose: 'fall', dur: 2.6 },
      { t: 2.6, do: 'move', who: 'helper', to: { near: 'faller', off: [1.2, 0.5] }, speed: 'jog' },
      { t: 3.8, do: 'pose', who: 'helper', pose: 'protest', dur: 1.2, face: 'faller' },
      { t: 5.2, do: 'release' },
    ],
    cues: [{ t: 0.6, signal: 'stumble', who: 'faller', dur: 0.8 }],
    decisive: 1.4,
    duration: 5.2,
    shots: [
      { from: 0, size: 'medium', subjects: ['faller'] },
      { from: 2.6, size: 'medium', subjects: ['faller', ['helper', 0.6]] },
    ],
  },
  {
    id: 'b-trashtalk',
    label: 'Trash talk',
    category: 'distraction',
    hint: 'Quei due se le stanno dicendo...',
    weight: 2,
    importance: 0.5,
    roles: {
      a: { label: 'Giocatore', pick: 'player', side: 'attack', roles: [...ALL], farFromBall: true },
      b: { label: 'Avversario', pick: 'player', side: 'defense', roles: [...ALL], near: 'a' },
      peacemaker: { label: 'Compagno', pick: 'player', side: 'attack', roles: [...ALL], near: 'a' },
    },
    steps: [
      { t: 0, do: 'move', who: 'a', to: { near: 'a' }, speed: 'walk' },
      { t: 0, do: 'move', who: 'b', to: { near: 'a', off: [1.3, 0] }, speed: 'jog' },
      { t: 1.4, do: 'pose', who: 'b', pose: 'argue', dur: 1.6, face: 'a' },
      { t: 3.0, do: 'pose', who: 'b', pose: 'shove', dur: 0.6, face: 'a' },
      { t: 3.2, do: 'move', who: 'a', to: { near: 'a', off: [-1.8, 0] }, speed: 'run' },
      { t: 3.3, do: 'pose', who: 'a', pose: 'stumble', dur: 0.8 },
      { t: 3.6, do: 'move', who: 'peacemaker', to: { near: 'a', off: [0.7, 0.8] }, speed: 'run' },
      { t: 4.4, do: 'pose', who: 'peacemaker', pose: 'protest', dur: 1.6, face: 'b' },
      { t: 4.6, do: 'pose', who: 'a', pose: 'argue', dur: 1.5, face: 'b' },
      { t: 6.4, do: 'release' },
    ],
    cues: [
      { t: 0.4, signal: 'argue', who: 'a', dur: 2.6 },
      { t: 2.0, signal: 'crowdRise', who: 'a' },
    ],
    decisive: 3.0,
    duration: 6.4,
    shots: [
      { from: 0, size: 'medium', subjects: ['a', 'b'] },
      { from: 3.6, size: 'medium', subjects: ['a', 'b', ['peacemaker', 0.6]] },
    ],
  },
  {
    id: 'b-invasione',
    label: 'Invasione di campo',
    category: 'distraction',
    hint: "C'è uno che scavalca!",
    weight: 1,
    importance: 0.8,
    exclusive: true,
    once: true,
    fixedSide: true,
    roles: {
      fan: { label: 'Tifoso', pick: 'extra', kind: 'fan', at: { pitch: [3, -12.5] } },
      s1: { label: 'Steward', pick: 'extra', kind: 'steward', at: { pitch: [-4, -12] } },
      s2: { label: 'Steward', pick: 'extra', kind: 'steward', at: { pitch: [9, -12] } },
      referee: { label: 'Arbitro', pick: 'referee' },
    },
    steps: [
      { t: 0, do: 'move', who: 'fan', to: { pitch: [2, -5] }, speed: 'sprint' },
      { t: 0.4, do: 'whistle' },
      { t: 0.6, do: 'pose', who: 'referee', pose: 'protest', dur: 1.5, face: 'fan' },
      { t: 1.0, do: 'follow', who: 's1', target: 'fan', off: [-1.2, -0.5], speed: 'run' },
      { t: 1.2, do: 'follow', who: 's2', target: 'fan', off: [1.2, -0.5], speed: 'run' },
      { t: 1.6, do: 'pose', who: 'fan', pose: 'wave', dur: 1.6 },
      { t: 2.0, do: 'move', who: 'fan', to: { pitch: [-3, 0] }, speed: 'sprint' },
      { t: 3.4, do: 'move', who: 'fan', to: { pitch: [3, 3] }, speed: 'sprint' },
      { t: 4.8, do: 'follow', who: 's1', target: 'fan', off: [-0.4, 0], speed: 'sprint' },
      { t: 5.1, do: 'pose', who: 's1', pose: 'tackle', dur: 1.0 },
      { t: 5.3, do: 'pose', who: 'fan', pose: 'fall', dur: 2.2 },
      { t: 7.5, do: 'move', who: 'fan', to: { pitch: [1, -12.5] }, speed: 'jog' },
      { t: 7.5, do: 'follow', who: 's1', target: 'fan', off: [-0.8, 0.5], speed: 'jog' },
      { t: 7.5, do: 'follow', who: 's2', target: 'fan', off: [0.8, 0.5], speed: 'jog' },
      { t: 8.5, do: 'restart', side: 'attack' },
    ],
    cues: [{ t: 0, signal: 'crowdRise', who: 'fan' }],
    decisive: 5.3,
    duration: 12,
    shots: [
      { from: 0, size: 'wide', subjects: ['fan'] },
      { from: 4.4, size: 'medium', subjects: ['fan', 's1'] },
      { from: 7.5, size: 'wide', subjects: ['fan', 's1', 's2'] },
    ],
  },
];
